export type Category = "Korallen" | "Fische" | "Wirbellose" | "Equipment" | "Frags";
export type Condition = "Nachzucht" | "Wildfang" | "Gebraucht" | "Neu";
export type ListingType = "B2C" | "C2C";

export interface Seller {
  id: string;
  name: string;
  avatar: string;
  rating: number;
  reviewCount: number;
  verified: boolean;
  type: "Händler" | "Privat";
  location: string;
  memberSince: string;
  salesCount: number;
  bio?: string;
}

export interface Listing {
  id: string;
  title: string;
  latin: string;
  price: number;
  currency: "CHF" | "EUR";
  subtitle: string;
  description: string;
  location: string;
  image: string;
  images: string[];
  category: Category;
  condition: Condition;
  listingType: ListingType;
  seller: Seller;
  tags: string[];
  postedAt: string;
  views: number;
  saved: boolean;
  badge?: string;
  shipping: boolean;
  shippingCost?: number;
  pickup: boolean;
}

// ─── Real marine-life image URLs ──────────────────────────────────────────────
// Pexels (free, no auth needed for direct linking in demos)
const IMG = {
  // Corals
  torchCoral:   "https://images.pexels.com/photos/1645028/pexels-photo-1645028.jpeg?auto=compress&cs=tinysrgb&w=1200",
  torchCoral2:  "https://images.pexels.com/photos/2765872/pexels-photo-2765872.jpeg?auto=compress&cs=tinysrgb&w=1200",
  zoanthus:     "https://images.pexels.com/photos/3854816/pexels-photo-3854816.jpeg?auto=compress&cs=tinysrgb&w=1200",
  acropora:     "https://images.pexels.com/photos/128756/pexels-photo-128756.jpeg?auto=compress&cs=tinysrgb&w=1200",
  acropora2:    "https://images.pexels.com/photos/3873954/pexels-photo-3873954.jpeg?auto=compress&cs=tinysrgb&w=1200",
  hammerCoral:  "https://images.pexels.com/photos/1583882/pexels-photo-1583882.jpeg?auto=compress&cs=tinysrgb&w=1200",
  bubbleCoral:  "https://images.pexels.com/photos/3682293/pexels-photo-3682293.jpeg?auto=compress&cs=tinysrgb&w=1200",
  softCoral:    "https://images.pexels.com/photos/3119711/pexels-photo-3119711.jpeg?auto=compress&cs=tinysrgb&w=1200",
  goniopora:    "https://images.pexels.com/photos/3854815/pexels-photo-3854815.jpeg?auto=compress&cs=tinysrgb&w=1200",
  candyCane:    "https://images.pexels.com/photos/3873955/pexels-photo-3873955.jpeg?auto=compress&cs=tinysrgb&w=1200",
  lpsColony:    "https://images.pexels.com/photos/1591447/pexels-photo-1591447.jpeg?auto=compress&cs=tinysrgb&w=1200",
  reefMix:      "https://images.pexels.com/photos/3873909/pexels-photo-3873909.jpeg?auto=compress&cs=tinysrgb&w=1200",
  // Fish
  clownfish:    "https://images.pexels.com/photos/2168831/pexels-photo-2168831.jpeg?auto=compress&cs=tinysrgb&w=1200",
  clownfish2:   "https://images.pexels.com/photos/2156311/pexels-photo-2156311.jpeg?auto=compress&cs=tinysrgb&w=1200",
  mandarinFish: "https://images.pexels.com/photos/3119720/pexels-photo-3119720.jpeg?auto=compress&cs=tinysrgb&w=1200",
  blueTang:     "https://images.pexels.com/photos/3119695/pexels-photo-3119695.jpeg?auto=compress&cs=tinysrgb&w=1200",
  wrasse:       "https://images.pexels.com/photos/3119704/pexels-photo-3119704.jpeg?auto=compress&cs=tinysrgb&w=1200",
  neonDottyback:"https://images.pexels.com/photos/3119710/pexels-photo-3119710.jpeg?auto=compress&cs=tinysrgb&w=1200",
  regalAngel:   "https://images.pexels.com/photos/3119714/pexels-photo-3119714.jpeg?auto=compress&cs=tinysrgb&w=1200",
  // Invertebrates
  giantClam:    "https://images.pexels.com/photos/3854820/pexels-photo-3854820.jpeg?auto=compress&cs=tinysrgb&w=1200",
  fireShrimp:   "https://images.pexels.com/photos/3854821/pexels-photo-3854821.jpeg?auto=compress&cs=tinysrgb&w=1200",
  cleanerShrimp:"https://images.pexels.com/photos/1591458/pexels-photo-1591458.jpeg?auto=compress&cs=tinysrgb&w=1200",
  bta:          "https://images.pexels.com/photos/2765871/pexels-photo-2765871.jpeg?auto=compress&cs=tinysrgb&w=1200",
  // Equipment
  ledLight:     "https://images.pexels.com/photos/4389982/pexels-photo-4389982.jpeg?auto=compress&cs=tinysrgb&w=1200",
  ledLight2:    "https://images.pexels.com/photos/6595767/pexels-photo-6595767.jpeg?auto=compress&cs=tinysrgb&w=1200",
  // Frags
  fragPack:     "https://images.pexels.com/photos/3873907/pexels-photo-3873907.jpeg?auto=compress&cs=tinysrgb&w=1200",
  fragsRack:    "https://images.pexels.com/photos/1645029/pexels-photo-1645029.jpeg?auto=compress&cs=tinysrgb&w=1200",
};

export const sellers: Seller[] = [
  {
    id: "s1",
    name: "CoralHaus Luzern",
    avatar: "https://i.pravatar.cc/150?img=3",
    rating: 4.9,
    reviewCount: 214,
    verified: true,
    type: "Händler",
    location: "Luzern",
    memberSince: "2019",
    salesCount: 1240,
    bio: "Professioneller Meerwasser-Händler mit Fokus auf LPS-Korallen, Anemonen und seltene Fische. CITES-konformer Handel, alle Tiere aus kontrollierten Systemen.",
  },
  {
    id: "s2",
    name: "Marc S.",
    avatar: "https://i.pravatar.cc/150?img=12",
    rating: 4.7,
    reviewCount: 38,
    verified: false,
    type: "Privat",
    location: "Zug",
    memberSince: "2022",
    salesCount: 47,
    bio: "Reef-Enthusiast seit 6 Jahren. Verkaufe Ableger aus meinem 800L Mixed-Reef.",
  },
  {
    id: "s3",
    name: "ReefLab Zürich",
    avatar: "https://i.pravatar.cc/150?img=7",
    rating: 5.0,
    reviewCount: 89,
    verified: true,
    type: "Händler",
    location: "Stans",
    memberSince: "2020",
    salesCount: 532,
    bio: "Spezialisiert auf SPS und Züchtung seltener Korallen. Wissenschaftlich fundierte Aquaristik.",
  },
  {
    id: "s4",
    name: "Nina B.",
    avatar: "https://i.pravatar.cc/150?img=25",
    rating: 4.8,
    reviewCount: 22,
    verified: false,
    type: "Privat",
    location: "Bern",
    memberSince: "2023",
    salesCount: 31,
    bio: "SPS-Liebhaberin, verkaufe Überschuss aus meinem Frag-System.",
  },
  {
    id: "s5",
    name: "OceanBreeder GmbH",
    avatar: "https://i.pravatar.cc/150?img=15",
    rating: 4.6,
    reviewCount: 177,
    verified: true,
    type: "Händler",
    location: "Basel",
    memberSince: "2018",
    salesCount: 2100,
    bio: "Schweizer Meerwasser-Züchter mit über 20 aktiven Nachzuchtsystemen.",
  },
  {
    id: "s6",
    name: "ReefAlliance Shop",
    avatar: "https://i.pravatar.cc/150?img=33",
    rating: 4.9,
    reviewCount: 312,
    verified: true,
    type: "Händler",
    location: "Zürich",
    memberSince: "2017",
    salesCount: 3200,
    bio: "ReefAlliance ist die führende Schweizer Plattform für Meerwasseraquaristik. Wir bieten Nachzuchten, Wildfang und Equipment von höchster Qualität. Alle Tiere akklimatisiert, CITES-konform, mit Gesundheitsgarantie.",
  },
  {
    id: "s7",
    name: "AquaCorals Winterthur",
    avatar: "https://i.pravatar.cc/150?img=52",
    rating: 4.8,
    reviewCount: 178,
    verified: true,
    type: "Händler",
    location: "Winterthur",
    memberSince: "2021",
    salesCount: 870,
    bio: "Spezialisierter Meerwasser-Fachhandel aus Winterthur mit eigenen Nachzuchtsystemen für LPS, SPS und Zoanthus. Alle Tiere werden bei uns futterfest akklimatisiert und mehrere Wochen quarantänisiert. CITES-konformer Handel, Lebendtiergarantie inklusive.",
  },
];

export const listings: Listing[] = [
  // ─── Existing listings (with real images) ─────────────────────────────────
  {
    id: "l1",
    title: "Dragon Soul Torch",
    latin: "Euphyllia glabrescens",
    price: 180,
    currency: "CHF",
    subtitle: "Hand selected frag – premium Orange/Gold coloration",
    description:
      "Absoluter Hingucker – diese Dragon Soul Torch zeigt ein sattes Orange-Gold mit leuchtenden Tips. Aus einem 3-jährig etablierten System mit stabilen Parametern. Polypengrösse 5+ cm, 3 Köpfe. Vollständig akklimatisiert auf NSW-Parameter. Ideal für SPS/LPS Mischriff.",
    location: "Luzern",
    image: IMG.torchCoral,
    images: [IMG.torchCoral, IMG.torchCoral2, IMG.lpsColony],
    category: "Korallen",
    condition: "Nachzucht",
    listingType: "B2C",
    seller: sellers[0],
    tags: ["LPS", "Euphyllia", "Premium", "WYSIWYG"],
    postedAt: "2h",
    views: 342,
    saved: false,
    badge: "Curated Drop",
    shipping: true,
    shippingCost: 28,
    pickup: true,
  },
  {
    id: "l2",
    title: "Oman Clown Pair",
    latin: "Amphiprion omanensis",
    price: 220,
    currency: "CHF",
    subtitle: "Seltenes Paar – fressen Pellets & Frozen",
    description:
      "Extrem seltenes Paar Oman-Clownfische (Amphiprion omanensis). Das Weibchen ist bereits deutlich grösser. Beide fressen Pellets und gefrorenes Futter. Nachzucht aus CH-Bestand, CITES-konform. Nur Selbstabholung, kein Versand.",
    location: "Zug",
    image: IMG.clownfish,
    images: [IMG.clownfish, IMG.clownfish2],
    category: "Fische",
    condition: "Nachzucht",
    listingType: "C2C",
    seller: sellers[1],
    tags: ["Clownfisch", "Paar", "Selten", "Nachzucht CH"],
    postedAt: "5h",
    views: 189,
    saved: true,
    shipping: false,
    pickup: true,
  },
  {
    id: "l3",
    title: "Ultra Zoanthus Garden",
    latin: "Zoanthus sp.",
    price: 95,
    currency: "CHF",
    subtitle: "150+ Polypen, WYSIWYG – Rot/Gelb/Pink-Rim",
    description:
      "Dichtes Zoanthus-Riff mit mind. 150+ Polypen auf 12×8 cm Stein. Farben: Rottöne, Gelb, Pink-Rim. Gesund, geschlossen getestet. Bereit für den sofortigen Umzug. Sehr pflegeleicht, ideal für Einsteiger und Fortgeschrittene.",
    location: "Stans",
    image: IMG.zoanthus,
    images: [IMG.zoanthus, IMG.reefMix],
    category: "Korallen",
    condition: "Nachzucht",
    listingType: "B2C",
    seller: sellers[2],
    tags: ["Zoanthus", "Ultra", "WYSIWYG", "Kolonie"],
    postedAt: "1d",
    views: 512,
    saved: false,
    badge: "Hot Deal",
    shipping: true,
    shippingCost: 22,
    pickup: true,
  },
  {
    id: "l4",
    title: "Acropora Tricolor",
    latin: "Acropora millepora",
    price: 145,
    currency: "CHF",
    subtitle: "Tri-color SPS – Grün/Blau/Pink Tips",
    description:
      "Spektakuläre Tricolor Acropora millepora – zeigt drei Farbtöne (Grün, Blau, Pink) je nach Beleuchtung. Frag ca. 5 cm, angebohrt auf Keramikhalter. Benötigt starke Strömung und Beleuchtung (>250 PAR).",
    location: "Bern",
    image: IMG.acropora,
    images: [IMG.acropora, IMG.acropora2],
    category: "Korallen",
    condition: "Nachzucht",
    listingType: "C2C",
    seller: sellers[3],
    tags: ["SPS", "Acropora", "Tricolor", "Frag"],
    postedAt: "2d",
    views: 278,
    saved: false,
    shipping: true,
    shippingCost: 28,
    pickup: false,
  },
  {
    id: "l5",
    title: "Mandarin Dragonet Paar",
    latin: "Synchiropus splendidus",
    price: 130,
    currency: "CHF",
    subtitle: "Frisst Frozen – extrem selten trainiert",
    description:
      "Mandarinfisch-Paar (m+w), fressen Frozen Copepods und Artemia. Dies ist extrem selten für diese Art. Aus 1500L System mit riesiger Copepodenpopulation. Aufzucht auf Tiefkühlware dauerte 4 Monate.",
    location: "Basel",
    image: IMG.mandarinFish,
    images: [IMG.mandarinFish],
    category: "Fische",
    condition: "Wildfang",
    listingType: "B2C",
    seller: sellers[4],
    tags: ["Mandarinfisch", "Paar", "Frisst Frozen"],
    postedAt: "3d",
    views: 421,
    saved: true,
    badge: "Selten",
    shipping: false,
    pickup: true,
  },
  {
    id: "l6",
    title: "Maxima Clam Electric Blue",
    latin: "Tridacna maxima",
    price: 290,
    currency: "CHF",
    subtitle: "10 cm Schalenbreite – leuchtend blauer Mantel",
    description:
      "Traumhafte Electric Blue Maxima-Muschel. Schalenbreite 10 cm, Mantel leuchtend blau mit dezenten Musterlinien. Aus 4-jährigem System. SPS-Bedingungen, Ca/Alk/Mg täglich gepflegt. Benötigt starkes Licht (400+ PAR).",
    location: "Luzern",
    image: IMG.giantClam,
    images: [IMG.giantClam],
    category: "Wirbellose",
    condition: "Wildfang",
    listingType: "B2C",
    seller: sellers[0],
    tags: ["Muschel", "Tridacna", "Electric Blue", "Showpiece"],
    postedAt: "4d",
    views: 198,
    saved: false,
    shipping: false,
    pickup: true,
  },
  {
    id: "l7",
    title: "AI Hydra 64 HD LED",
    latin: "",
    price: 480,
    currency: "CHF",
    subtitle: "18 Monate alt – alle Kanäle perfekt",
    description:
      "AI Hydra 64 HD LED-Leuchte inkl. originalem Flexarm. Ca. 18 Monate alt, nur auf SPS-Tank betrieben. Alle Kanäle funktionieren, sehr gute Lichtleistung. Kein Versand, Abholung in Zug oder Raum Zentralschweiz.",
    location: "Zug",
    image: IMG.ledLight,
    images: [IMG.ledLight, IMG.ledLight2],
    category: "Equipment",
    condition: "Gebraucht",
    listingType: "C2C",
    seller: sellers[1],
    tags: ["LED", "AI Hydra", "Beleuchtung", "SPS"],
    postedAt: "5d",
    views: 89,
    saved: false,
    shipping: false,
    pickup: true,
  },
  {
    id: "l8",
    title: "Blasenpilz Grün/Pink",
    latin: "Plerogyra sinuosa",
    price: 65,
    currency: "CHF",
    subtitle: "Pflegeleicht – grüne Blasen, pink Gewebe",
    description:
      "Plerogyra sinuosa, grüne Blasen mit pink-violettem Gewebe. Sehr pflegeleichte LPS-Koralle für Einsteiger. Frag ca. 6 cm mit 2 Köpfen. Ideal für niedrige bis mittlere Licht- und Strömungszonen.",
    location: "Stans",
    image: IMG.bubbleCoral,
    images: [IMG.bubbleCoral, IMG.softCoral],
    category: "Korallen",
    condition: "Nachzucht",
    listingType: "B2C",
    seller: sellers[2],
    tags: ["LPS", "Blasenpilz", "Einsteiger"],
    postedAt: "6d",
    views: 156,
    saved: false,
    shipping: true,
    shippingCost: 22,
    pickup: true,
  },

  // ─── ReefAlliance B2C Shop Listings ──────────────────────────────────────
  {
    id: "ra1",
    title: "Royal Blue Tang",
    latin: "Paracanthurus hepatus",
    price: 155,
    currency: "CHF",
    subtitle: "Akklimatisiert, frisst Pellets – 7 cm",
    description:
      "Gesunder Royal Blue Tang (Paracanthurus hepatus), ca. 7 cm. Vollständig akklimatisiert, frisst trockenes und gefrorenes Futter. Quarantänisiert für 21 Tage, keine Erkrankungen. Benötigt mind. 300L und reichlich Schwimmraum. Versand mit Thermobox möglich.",
    location: "Zürich",
    image: IMG.blueTang,
    images: [IMG.blueTang],
    category: "Fische",
    condition: "Wildfang",
    listingType: "B2C",
    seller: sellers[5],
    tags: ["Doktorfisch", "Blue Tang", "Frisst Pellets", "Quarantänisiert"],
    postedAt: "1h",
    views: 284,
    saved: false,
    badge: "Top Qualität",
    shipping: true,
    shippingCost: 35,
    pickup: true,
  },
  {
    id: "ra2",
    title: "Hammer Coral – Gold/Green",
    latin: "Euphyllia ancora",
    price: 75,
    currency: "CHF",
    subtitle: "Frag 3 Köpfe – Gold-grüne Spitzen",
    description:
      "Wunderschöne Euphyllia ancora (Hammer-Koralle) mit goldgrünen Hammerspitzen und hellgrünem Gewebe. 3 Köpfe auf Keramikhalter, ca. 8 cm. Nachzucht aus unserem System, etabliert seit 2 Jahren. Sehr robust, für Einsteiger geeignet.",
    location: "Zürich",
    image: IMG.hammerCoral,
    images: [IMG.hammerCoral, IMG.lpsColony],
    category: "Korallen",
    condition: "Nachzucht",
    listingType: "B2C",
    seller: sellers[5],
    tags: ["LPS", "Euphyllia", "Hammer", "Nachzucht"],
    postedAt: "3h",
    views: 198,
    saved: false,
    shipping: true,
    shippingCost: 28,
    pickup: true,
  },
  {
    id: "ra3",
    title: "Sixline Wrasse",
    latin: "Pseudocheilinus hexataenia",
    price: 78,
    currency: "CHF",
    subtitle: "Lebendig farbenfroh – natürliche Schädlingsbekämpfung",
    description:
      "Pseudocheilinus hexataenia – einer der schönsten Lippfische für das Riff. Frisst Milben, Strudelfüsser und andere Parasiten. Akklimatisiert, frisst gefrorenes Futter. Ideale Ergänzung für Korallen- und LPS-Becken ab 150L.",
    location: "Zürich",
    image: IMG.wrasse,
    images: [IMG.wrasse],
    category: "Fische",
    condition: "Wildfang",
    listingType: "B2C",
    seller: sellers[5],
    tags: ["Lippfisch", "Wrasse", "Schädlingsbekämpfung", "Riff-sicher"],
    postedAt: "5h",
    views: 134,
    saved: false,
    shipping: true,
    shippingCost: 35,
    pickup: true,
  },
  {
    id: "ra4",
    title: "Pacific Cleaner Shrimp Duo",
    latin: "Lysmata amboinensis",
    price: 52,
    currency: "CHF",
    subtitle: "2er-Set – Putzerstation für dein Becken",
    description:
      "Zwei Lysmata amboinensis (Rote Putzer-Garnele) – bilden eine natürliche Putzstation. Fressen Parasiten von Fischen und halten das Becken gesund. Sehr robust, für alle Riff-Beckengrössen geeignet. Inkl. Lebendtransport-Garantie.",
    location: "Zürich",
    image: IMG.cleanerShrimp,
    images: [IMG.cleanerShrimp],
    category: "Wirbellose",
    condition: "Wildfang",
    listingType: "B2C",
    seller: sellers[5],
    tags: ["Garnele", "Cleaner", "Putzstation", "Riff-sicher"],
    postedAt: "1d",
    views: 165,
    saved: false,
    shipping: true,
    shippingCost: 28,
    pickup: true,
  },
  {
    id: "ra5",
    title: "Duncan Coral Kolonie",
    latin: "Duncanopsammia axifuga",
    price: 120,
    currency: "CHF",
    subtitle: "8 Köpfe – bewegliche Tentakel, einfach zu halten",
    description:
      "Duncanopsammia axifuga mit 8 ausgewachsenen Köpfen. Wunderschöne grüne Tentakel mit leuchtenden Spitzen. Eine der pflegeleichtesten LPS-Korallen – ideal für Einsteiger. Niedrige bis mittlere Strömung und Beleuchtung.",
    location: "Zürich",
    image: IMG.lpsColony,
    images: [IMG.lpsColony, IMG.reefMix],
    category: "Korallen",
    condition: "Nachzucht",
    listingType: "B2C",
    seller: sellers[5],
    tags: ["LPS", "Duncan", "Einsteiger", "Kolonie"],
    postedAt: "1d",
    views: 221,
    saved: false,
    badge: "Bestseller",
    shipping: true,
    shippingCost: 28,
    pickup: true,
  },
  {
    id: "ra6",
    title: "Goniopora – Blumenpilz Pink",
    latin: "Goniopora sp.",
    price: 89,
    currency: "CHF",
    subtitle: "Frag 2 Köpfe – seltene pinke Variante",
    description:
      "Goniopora sp. in seltener pinker Färbung. Lange, sich wiegende Tentakel mit weissem Zentrum. Frag auf Keramikhalter, 2 Köpfe. Benötigt moderate Beleuchtung und niedrige Strömung. Aus unserem Nachzuchtsystem.",
    location: "Zürich",
    image: IMG.goniopora,
    images: [IMG.goniopora],
    category: "Korallen",
    condition: "Nachzucht",
    listingType: "B2C",
    seller: sellers[5],
    tags: ["LPS", "Goniopora", "Pink", "Blumenpilz"],
    postedAt: "2d",
    views: 178,
    saved: false,
    shipping: true,
    shippingCost: 28,
    pickup: true,
  },
  {
    id: "ra7",
    title: "Riff-Starter Frags Set",
    latin: "Mix Euphyllia / Zoanthus / SPS",
    price: 145,
    currency: "CHF",
    subtitle: "6 Frags – kuratiertes Einsteiger-Paket",
    description:
      "Das perfekte Starter-Paket für dein erstes Riff: 6 Frags bestehend aus 2x Zoanthus, 2x LPS (Hammer/Torch), 1x SPS (Montipora), 1x Softkoral. Alle auf Keramikhaltern, klar beschriftet mit Pflegeinfos. Versand in Thermobox inklusive.",
    location: "Zürich",
    image: IMG.fragPack,
    images: [IMG.fragPack, IMG.fragsRack, IMG.reefMix],
    category: "Frags",
    condition: "Nachzucht",
    listingType: "B2C",
    seller: sellers[5],
    tags: ["Starter", "Set", "Mix", "Frags", "Einsteiger"],
    postedAt: "2d",
    views: 389,
    saved: false,
    badge: "Neu",
    shipping: true,
    shippingCost: 35,
    pickup: true,
  },
  {
    id: "ra8",
    title: "Candy Cane Coral",
    latin: "Caulastrea furcata",
    price: 58,
    currency: "CHF",
    subtitle: "Frag 4 Köpfe – grün/weiss, sehr robust",
    description:
      "Caulastrea furcata (Candy Cane/Trompeten-Koralle) in klassischer grün-weiss Zeichnung. 4 Köpfe auf Keramikhalter. Extrem robust und pflegeleicht, verzeiht kurzfristige Parameterschwankungen. Ideal für kleine bis mittlere Becken.",
    location: "Zürich",
    image: IMG.candyCane,
    images: [IMG.candyCane],
    category: "Korallen",
    condition: "Nachzucht",
    listingType: "B2C",
    seller: sellers[5],
    tags: ["LPS", "Caulastrea", "Einsteiger", "Robust"],
    postedAt: "3d",
    views: 142,
    saved: false,
    shipping: true,
    shippingCost: 22,
    pickup: true,
  },
  {
    id: "ra9",
    title: "Rose Bubble Tip Anemone",
    latin: "Entacmaea quadricolor",
    price: 68,
    currency: "CHF",
    subtitle: "Roséfarben – idealer Clownfisch-Host",
    description:
      "Entacmaea quadricolor in schöner rosé/lachs Färbung mit aufgeblasenen Blasentips. Perfekter Wirt für Clownfische. Aus unserem etablierten 600L System. Grösse ca. 10 cm geöffnet. Benötigt starkes Licht und gute Wasserqualität.",
    location: "Zürich",
    image: IMG.bta,
    images: [IMG.bta],
    category: "Wirbellose",
    condition: "Nachzucht",
    listingType: "B2C",
    seller: sellers[5],
    tags: ["Anemone", "BTA", "Clownfisch", "Nachzucht"],
    postedAt: "4d",
    views: 256,
    saved: false,
    badge: "Beliebt",
    shipping: false,
    pickup: true,
  },
  {
    id: "ra10",
    title: "Acropora Frag – Neon Green",
    latin: "Acropora tenuis",
    price: 95,
    currency: "CHF",
    subtitle: "Neon-grüne SPS – schnelles Wachstum",
    description:
      "Acropora tenuis in strahlend neongrüner Färbung. Schnellwachsend, ca. 5–6 cm auf Keramikhalter. Aus unserem SPS-Zuchtbecken, akklimatisiert auf stabile Parameter. Für erfahrene SPS-Keeper. PAR 200–400, Alkalinität 8–9 dKH.",
    location: "Zürich",
    image: IMG.acropora2,
    images: [IMG.acropora2, IMG.acropora],
    category: "Frags",
    condition: "Nachzucht",
    listingType: "B2C",
    seller: sellers[5],
    tags: ["SPS", "Acropora", "Neon Green", "Frag"],
    postedAt: "5d",
    views: 193,
    saved: false,
    shipping: true,
    shippingCost: 28,
    pickup: true,
  },

  // ─── AquaCorals Winterthur – 20 Inserate ─────────────────────────────────
  {
    id: "cw1",
    title: "Gold Torch – Ora Gold Edition",
    latin: "Euphyllia glabrescens",
    price: 95,
    currency: "CHF",
    subtitle: "2 Köpfe – sattgoldene Tentakel, leuchtende Tips",
    description:
      "Diese Taschenlampenkoralle zeigt eine aussergewöhnliche Gold-Orange-Färbung mit strahlend weissen Tentakelspitzen. 2 ausgewachsene Köpfe auf Keramikhalter, Polypengrösse je 4–5 cm. Aus unserem seit 3 Jahren laufenden LPS-Nachzuchtsystem. Robuste Art für Einsteiger und Fortgeschrittene – verträgt moderate Strömung und mittleres bis starkes Licht. Alk 8–9 dKH, Ca 420–440, Mg 1300–1350.",
    location: "Winterthur",
    image: IMG.torchCoral,
    images: [IMG.torchCoral, IMG.torchCoral2],
    category: "Korallen",
    condition: "Nachzucht",
    listingType: "B2C",
    seller: sellers[6],
    tags: ["LPS", "Euphyllia", "Torch", "Gold", "WYSIWYG"],
    postedAt: "2h",
    views: 312,
    saved: false,
    badge: "WYSIWYG",
    shipping: true,
    shippingCost: 28,
    pickup: true,
  },
  {
    id: "cw2",
    title: "Ultra Pink Hammer",
    latin: "Euphyllia ancora",
    price: 88,
    currency: "CHF",
    subtitle: "3 Köpfe – Pink/Lila Hammerköpfe, robuste Nachzucht",
    description:
      "Euphyllia ancora in leuchtend pinker Färbung mit violetten Tentakelenden – eine der begehrtesten LPS-Farbvarianten. 3 Köpfe auf Keramikhalter, Polypengrösse ca. 4 cm. Aus eigenem Nachzuchtsystem, seit 14 Monaten etabliert. Sehr pflegeleicht, ideal für LPS-Riff. Niedrige bis moderate Strömung, mittlere Beleuchtung (100–150 PAR). Versand in Thermobox mit Wärmepack.",
    location: "Winterthur",
    image: IMG.hammerCoral,
    images: [IMG.hammerCoral, IMG.lpsColony],
    category: "Korallen",
    condition: "Nachzucht",
    listingType: "B2C",
    seller: sellers[6],
    tags: ["LPS", "Euphyllia", "Hammer", "Pink", "Nachzucht"],
    postedAt: "4h",
    views: 246,
    saved: false,
    shipping: true,
    shippingCost: 28,
    pickup: true,
  },
  {
    id: "cw3",
    title: "Rainbow Brain Coral",
    latin: "Trachyphyllia geoffroyi",
    price: 115,
    currency: "CHF",
    subtitle: "Einzelpolype – Rot/Grün/Blau, WYSIWYG Wildfang",
    description:
      "Spektakuläre Trachyphyllia geoffroyi mit einem dreifarbigen Muster aus Rot, Grün und Blautönen. Durchmesser ca. 7 cm, gut etabliert in unseren Systemen. Benötigt niedrige bis moderate Strömung und moderates Licht (80–150 PAR). Frisst Frozen Mysis und Pellets. WYSIWYG – das abgebildete Exemplar ist genau das, das du erhältst.",
    location: "Winterthur",
    image: IMG.lpsColony,
    images: [IMG.lpsColony, IMG.reefMix],
    category: "Korallen",
    condition: "Wildfang",
    listingType: "B2C",
    seller: sellers[6],
    tags: ["LPS", "Trachyphyllia", "Brain", "WYSIWYG", "Wildfang"],
    postedAt: "6h",
    views: 189,
    saved: false,
    badge: "WYSIWYG",
    shipping: false,
    pickup: true,
  },
  {
    id: "cw4",
    title: "Blastomussa Ultra Color",
    latin: "Blastomussa wellsi",
    price: 68,
    currency: "CHF",
    subtitle: "5 Polypen – Rot/Blau/Grün, einfach & schnell wachsend",
    description:
      "Blastomussa wellsi in einer farbenfrohen Multicolor-Variante mit roten, blauen und grünen Polypen auf einem Stein. 5 ausgewachsene Polypen, Durchmesser 2–3 cm je Polype. Sehr pflegeleichte LPS-Koralle, die auch unter suboptimalen Bedingungen gedeiht. Ideale Koralle für Becken mit niedrigem bis mittlerem Licht und ruhiger Strömung. Wächst gut und teilt regelmässig.",
    location: "Winterthur",
    image: IMG.goniopora,
    images: [IMG.goniopora, IMG.reefMix],
    category: "Korallen",
    condition: "Nachzucht",
    listingType: "B2C",
    seller: sellers[6],
    tags: ["LPS", "Blastomussa", "Multicolor", "Einsteiger"],
    postedAt: "1d",
    views: 143,
    saved: false,
    shipping: true,
    shippingCost: 22,
    pickup: true,
  },
  {
    id: "cw5",
    title: "Frogspawn Coral – Neon Green",
    latin: "Euphyllia divisa",
    price: 78,
    currency: "CHF",
    subtitle: "4 Köpfe – Neongrün mit weissen Tips",
    description:
      "Euphyllia divisa (Traubenkoralle) in satten Neongrüntönen mit leuchtend weissen Tentakelenden – ein absolutes Highlight im LPS-Riff. 4 Köpfe auf Keramikhalter. Aus unserem Nachzuchtsystem, 2 Jahre akklimatisiert. Die wogenden Tentakel erzeugen eine traumhafte Bewegung im Becken. Niedrige bis moderate Strömung, 80–180 PAR. Sehr beliebt als Centerpiece.",
    location: "Winterthur",
    image: IMG.bubbleCoral,
    images: [IMG.bubbleCoral, IMG.softCoral],
    category: "Korallen",
    condition: "Nachzucht",
    listingType: "B2C",
    seller: sellers[6],
    tags: ["LPS", "Euphyllia", "Frogspawn", "Neon Green"],
    postedAt: "1d",
    views: 198,
    saved: false,
    shipping: true,
    shippingCost: 28,
    pickup: true,
  },
  {
    id: "cw6",
    title: "Montipora capricornis – Orange Plate",
    latin: "Montipora capricornis",
    price: 58,
    currency: "CHF",
    subtitle: "Plattenfrag 8 cm – leuchtendes Orange, SPS-Einsteiger",
    description:
      "Montipora capricornis in strahlendem Orange. Diese plattenförmig wachsende SPS-Koralle eignet sich hervorragend als Einstieg in die SPS-Aquaristik – weniger anspruchsvoll als Acropora, aber genauso beeindruckend. Frag ca. 8 cm, auf Keramikhalter. Schnellwachsend, benötigt moderate bis starke Beleuchtung (180–300 PAR) und mittlere Strömung.",
    location: "Winterthur",
    image: IMG.acropora2,
    images: [IMG.acropora2],
    category: "Korallen",
    condition: "Nachzucht",
    listingType: "B2C",
    seller: sellers[6],
    tags: ["SPS", "Montipora", "Orange", "Einsteiger"],
    postedAt: "2d",
    views: 127,
    saved: false,
    shipping: true,
    shippingCost: 22,
    pickup: true,
  },
  {
    id: "cw7",
    title: "Acropora millepora – Pink Lemonade",
    latin: "Acropora millepora",
    price: 128,
    currency: "CHF",
    subtitle: "Frag 5 cm – Pink/Gelb, bewährte Schweizer Nachzucht",
    description:
      "Acropora millepora 'Pink Lemonade' – eine der farbenfrohsten Nachzuchtvarianten. Zeigt zartes Rosa bis Pink mit leuchtend gelben Asttips. Frag ca. 5 cm auf Keramikhalter, aus unserem SPS-Stammbecken mit täglicher ICP-geprüfter Wasserqualität. Benötigt starkes Licht (250–400 PAR), hohe Strömung und stabile Alkalinität (8–9 dKH). Für erfahrene SPS-Aquarianer.",
    location: "Winterthur",
    image: IMG.acropora,
    images: [IMG.acropora, IMG.acropora2],
    category: "Frags",
    condition: "Nachzucht",
    listingType: "B2C",
    seller: sellers[6],
    tags: ["SPS", "Acropora", "Millepora", "Pink Lemonade", "Frag"],
    postedAt: "3h",
    views: 274,
    saved: false,
    badge: "Hot",
    shipping: true,
    shippingCost: 28,
    pickup: true,
  },
  {
    id: "cw8",
    title: "Zoanthus \"Dragon Eye\"",
    latin: "Zoanthus sp.",
    price: 38,
    currency: "CHF",
    subtitle: "5 Polypen – Goldgelb mit grünem Zentrum",
    description:
      "Zoanthus 'Dragon Eye' – wunderschöne Farbmorphe mit tiefgelbem bis goldorangem Rand und knallgrünem Zentrum. 5 Polypen auf Fragstein aus Schweizer Nachzucht, Polypengrösse ca. 1–1.5 cm. Sehr pflegeleicht, wächst unter fast allen Bedingungen und eignet sich ideal für Einsteiger. Niedrige bis starke Beleuchtung, wenig bis viel Strömung.",
    location: "Winterthur",
    image: IMG.zoanthus,
    images: [IMG.zoanthus, IMG.fragsRack],
    category: "Frags",
    condition: "Nachzucht",
    listingType: "B2C",
    seller: sellers[6],
    tags: ["Zoanthus", "Dragon Eye", "Frag", "Einsteiger"],
    postedAt: "5h",
    views: 321,
    saved: false,
    shipping: true,
    shippingCost: 22,
    pickup: true,
  },
  {
    id: "cw9",
    title: "Zoanthus \"Alien Antivenom\"",
    latin: "Zoanthus sp.",
    price: 42,
    currency: "CHF",
    subtitle: "4 Polypen – Grün/Gelb, Schweizer Nachzucht mit Anwachsgarantie",
    description:
      "Zoanthus 'Alien Antivenom' – eine der begehrtesten Zoanthus-Morphen mit intensiv gelbgrünem Rand und kontrastierendem dunklem Zentrum. 4 Polypen aus garantierter Schweizer Nachzucht auf Keramikhalter. Vollständig akklimatisiert, sehr robust und schnell wachsend. 30 Tage Anwachsgarantie. Versand mit Swiss Express Mond möglich.",
    location: "Winterthur",
    image: IMG.zoanthus,
    images: [IMG.zoanthus],
    category: "Frags",
    condition: "Nachzucht",
    listingType: "B2C",
    seller: sellers[6],
    tags: ["Zoanthus", "Alien Antivenom", "Frag", "Nachzucht CH"],
    postedAt: "8h",
    views: 287,
    saved: false,
    badge: "Beliebt",
    shipping: true,
    shippingCost: 22,
    pickup: true,
  },
  {
    id: "cw10",
    title: "Palythoa \"Grandis Blue\"",
    latin: "Palythoa grandis",
    price: 35,
    currency: "CHF",
    subtitle: "6 Polypen – Blaugrau, gross und imposant",
    description:
      "Palythoa grandis 'Blue' – grosspolyp mit bis zu 3 cm Polypendurchmesser in blaugrauer Färbung mit leicht schimmerndem Schleier. 6 Polypen auf Fragstein. Achtung: Palytoxin-Träger – bei der Handhabung Handschuhe tragen! Sehr pflegeleicht und robust, ideal für niedrige Strömungszonen. Wächst schnell und teilt gut.",
    location: "Winterthur",
    image: IMG.fragPack,
    images: [IMG.fragPack, IMG.fragsRack],
    category: "Frags",
    condition: "Nachzucht",
    listingType: "B2C",
    seller: sellers[6],
    tags: ["Palythoa", "Zoanthus", "Frag", "Grosspolype"],
    postedAt: "1d",
    views: 165,
    saved: false,
    shipping: true,
    shippingCost: 22,
    pickup: true,
  },
  {
    id: "cw11",
    title: "Frag-Starter-Set 8× WYSIWYG",
    latin: "Mix SPS / LPS / Zoanthus",
    price: 158,
    currency: "CHF",
    subtitle: "8 handverlesene Frags – perfekt für Neueinsteiger",
    description:
      "Unser kuratiertes Einsteiger-Paket mit 8 verschiedenen Frags aus unserem Bestand: 3× Zoanthus (verschiedene Farbmorphen), 2× LPS (Euphyllia/Blastomussa), 2× Soft Coral (Sinularia/Xenia), 1× SPS (Montipora). Alle Frags auf Keramikhaltern, klar etikettiert mit Pflegeanforderungen. Versand in Styroporbox mit Wärmepack inkl. Lebendtiergarantie.",
    location: "Winterthur",
    image: IMG.fragsRack,
    images: [IMG.fragsRack, IMG.fragPack, IMG.reefMix],
    category: "Frags",
    condition: "Nachzucht",
    listingType: "B2C",
    seller: sellers[6],
    tags: ["Starter", "Set", "Mix", "WYSIWYG", "Einsteiger"],
    postedAt: "2d",
    views: 412,
    saved: false,
    badge: "Bestseller",
    shipping: true,
    shippingCost: 35,
    pickup: true,
  },
  {
    id: "cw12",
    title: "Clownfisch-Paar Nachzucht",
    latin: "Amphiprion ocellaris",
    price: 78,
    currency: "CHF",
    subtitle: "Weibchen + Männchen – frisst Pellets & Frozen",
    description:
      "Klassisches Clownfisch-Paar (Amphiprion ocellaris) aus zertifizierter Schweizer Nachzucht. Das Weibchen ist bereits ca. 5 cm, das Männchen ca. 3.5 cm. Beide fressen Pellets und Tiefkühlfutter problemlos. Vollständig akklimatisiert, sehr robust. Halten sich gerne in Anemonen (BTA, RBTA) oder Weichkorallen. Ideal für Becken ab 100L.",
    location: "Winterthur",
    image: IMG.clownfish,
    images: [IMG.clownfish, IMG.clownfish2],
    category: "Fische",
    condition: "Nachzucht",
    listingType: "B2C",
    seller: sellers[6],
    tags: ["Clownfisch", "Paar", "Nachzucht CH", "Frisst Pellets"],
    postedAt: "4h",
    views: 389,
    saved: false,
    badge: "Nachzucht CH",
    shipping: true,
    shippingCost: 35,
    pickup: true,
  },
  {
    id: "cw13",
    title: "Neon-Grundel Putzer",
    latin: "Elacatinus oceanops",
    price: 42,
    currency: "CHF",
    subtitle: "Lebhafter Reiniger – neonblauer Streifen",
    description:
      "Elacatinus oceanops (Neon-Grundel) – ein kleiner, lebhafter Putzer mit strahlendem Neonblaustreifen. Frisst Parasiten von Fischen und hilft die natürliche Putzstation im Becken zu etablieren. Ideal für Becken ab 60L, verträgt sich gut mit anderen friedlichen Fischen. Akklimatisiert, frisst Pellets und gefrorenes Futter.",
    location: "Winterthur",
    image: IMG.neonDottyback,
    images: [IMG.neonDottyback],
    category: "Fische",
    condition: "Wildfang",
    listingType: "B2C",
    seller: sellers[6],
    tags: ["Grundel", "Putzer", "Riff-sicher", "Nano"],
    postedAt: "1d",
    views: 134,
    saved: false,
    shipping: true,
    shippingCost: 35,
    pickup: true,
  },
  {
    id: "cw14",
    title: "Gelb-Schwanz-Demoiselle",
    latin: "Chrysiptera parasema",
    price: 35,
    currency: "CHF",
    subtitle: "Pflegeleicht, lebendig – ideal für Einsteiger",
    description:
      "Chrysiptera parasema – einer der wenigen Demoisellen, der als relativ friedlich gilt. Leuchtend blauer Körper mit knallgelbem Schwanz. Sehr robust, frisst alles, ideal für Einsteiger in die Meerwasseraquaristik. Akklimatisiert, frisst Pellets und Frozen. Für Becken ab 100L. Riff-sicher, beisst keine Korallen an.",
    location: "Winterthur",
    image: IMG.blueTang,
    images: [IMG.blueTang],
    category: "Fische",
    condition: "Wildfang",
    listingType: "B2C",
    seller: sellers[6],
    tags: ["Demoiselle", "Einsteiger", "Riff-sicher", "Robust"],
    postedAt: "2d",
    views: 98,
    saved: false,
    shipping: true,
    shippingCost: 35,
    pickup: true,
  },
  {
    id: "cw15",
    title: "Roter Feuerpfeil-Grundel",
    latin: "Nemateleotris magnifica",
    price: 62,
    currency: "CHF",
    subtitle: "Leuchtend Rot/Weiss – atemberaubendes Flossenspiel",
    description:
      "Nemateleotris magnifica (Feuerpfeil-Grundel) – einer der schönsten Meerwasserfische überhaupt. Leuchtend weisser Körper mit sattem Rot/Orange am Hinterkörper und feiner, sich ständig bewegender erster Rückenflosse. Sehr friedlicher Charakter, ideal für Riffbecken. Frisst Pellets und Frozen Mysis. Für Becken ab 100L, am besten paarweise halten.",
    location: "Winterthur",
    image: IMG.wrasse,
    images: [IMG.wrasse],
    category: "Fische",
    condition: "Wildfang",
    listingType: "B2C",
    seller: sellers[6],
    tags: ["Grundel", "Feuerpfeil", "Friedlich", "Riff-sicher"],
    postedAt: "3d",
    views: 176,
    saved: false,
    shipping: true,
    shippingCost: 35,
    pickup: true,
  },
  {
    id: "cw16",
    title: "Tridacna squamosa – Multicolor",
    latin: "Tridacna squamosa",
    price: 185,
    currency: "CHF",
    subtitle: "Schalenbreite 8 cm – Braun/Gold/Grün Mantel, WYSIWYG",
    description:
      "Beeindruckende Tridacna squamosa (Schuppige Riesenmuschel) mit einem gemusterten Mantel in Braun-, Gold- und Grüntönen. Schalenbreite ca. 8 cm, gut etabliert. Benötigt starkes Licht (mind. 200 PAR an der Bodenposition) und gute Wasserqualität. Filtert aktiv, keine Fütterung nötig. WYSIWYG – das abgebildete Exemplar ist genau das, das du erhältst.",
    location: "Winterthur",
    image: IMG.giantClam,
    images: [IMG.giantClam],
    category: "Wirbellose",
    condition: "Wildfang",
    listingType: "B2C",
    seller: sellers[6],
    tags: ["Muschel", "Tridacna", "WYSIWYG", "Filterfeeder"],
    postedAt: "2h",
    views: 223,
    saved: false,
    badge: "WYSIWYG",
    shipping: false,
    pickup: true,
  },
  {
    id: "cw17",
    title: "Fire Shrimp – Blutroter Putzergarnele",
    latin: "Lysmata debelius",
    price: 58,
    currency: "CHF",
    subtitle: "Sattrot mit weissen Antennen – natürliche Putzstation",
    description:
      "Lysmata debelius (Feuergarnele) in sattem Blutrot mit charakteristischen langen weissen Antennen und weissen Punkten. Eine der eindrucksvollsten und langlebigsten Garnelen im Meerwasseraquarium. Frisst Parasiten von Fischen, ideal als Putzstation. Für Becken ab 80L, friedlich mit Korallen und anderen Wirbellosen.",
    location: "Winterthur",
    image: IMG.fireShrimp,
    images: [IMG.fireShrimp],
    category: "Wirbellose",
    condition: "Wildfang",
    listingType: "B2C",
    seller: sellers[6],
    tags: ["Garnele", "Fire Shrimp", "Putzstation", "Riff-sicher"],
    postedAt: "1d",
    views: 142,
    saved: false,
    shipping: true,
    shippingCost: 28,
    pickup: true,
  },
  {
    id: "cw18",
    title: "Roter Seestern",
    latin: "Fromia milleporella",
    price: 45,
    currency: "CHF",
    subtitle: "Leuchtend rot – frisst Algen und Detritus",
    description:
      "Fromia milleporella (Roter Seestern) in tiefem Scharlachrot. Frisst Algen, Biofilm und Detritus und hilft dabei, den Bodengrund sauber zu halten. Friedlich, riff-sicher. Benötigt stabile Wasserqualität (kein Kupfer!) und ausreichend Futter im Becken. Akklimatisierung langsam durchführen. Durchmesser ca. 7 cm.",
    location: "Winterthur",
    image: IMG.cleanerShrimp,
    images: [IMG.cleanerShrimp],
    category: "Wirbellose",
    condition: "Wildfang",
    listingType: "B2C",
    seller: sellers[6],
    tags: ["Seestern", "Putzertier", "Riff-sicher", "Algenfrasser"],
    postedAt: "3d",
    views: 88,
    saved: false,
    shipping: false,
    pickup: true,
  },
  {
    id: "cw19",
    title: "Nyos Quantum 120 Abschäumer",
    latin: "",
    price: 295,
    currency: "CHF",
    subtitle: "Für Becken bis 300L – top Zustand, 14 Monate alt",
    description:
      "Nyos Quantum 120 Proteinabschäumer in sehr gutem Zustand. Nur 14 Monate benutzt, regelmässig gewartet und gereinigt. Geeignet für Becken bis 300L (Herstellerangabe). Lieferung inkl. Originalkarton und allen Teilen. Kein Rückgabe, Verkauf wie besehen. Abholung in Winterthur oder Versand auf Käuferrisiko.",
    location: "Winterthur",
    image: IMG.ledLight2,
    images: [IMG.ledLight2, IMG.ledLight],
    category: "Equipment",
    condition: "Gebraucht",
    listingType: "B2C",
    seller: sellers[6],
    tags: ["Abschäumer", "Nyos", "Quantum", "Sump"],
    postedAt: "4d",
    views: 112,
    saved: false,
    shipping: true,
    shippingCost: 18,
    pickup: true,
  },
  {
    id: "cw20",
    title: "Ecotech VorTech MP10 QD",
    latin: "",
    price: 168,
    currency: "CHF",
    subtitle: "Quiet Drive – kabelloser Antrieb, neuwertig",
    description:
      "Ecotech Marine VorTech MP10 Quiet Drive Strömungspumpe in neuwertigem Zustand. Kabelloser Antrieb, stufenlos regelbar, kompatibel mit ReefLink und EcoSmart Ecosystem. Alle Gummidichtungen intakt, Propeller und Magnete ohne Beschädigungen. Ideal für Becken von 75–280L. Lieferung mit Originalkarton, allen Teilen und Netzteil. 6 Monate alt.",
    location: "Winterthur",
    image: IMG.ledLight,
    images: [IMG.ledLight, IMG.ledLight2],
    category: "Equipment",
    condition: "Gebraucht",
    listingType: "B2C",
    seller: sellers[6],
    tags: ["Strömungspumpe", "Ecotech", "VorTech", "MP10"],
    postedAt: "5d",
    views: 143,
    saved: false,
    shipping: true,
    shippingCost: 12,
    pickup: true,
  },
];

export const categories: { label: Category | "Alle"; icon: string; count: number }[] = [
  { label: "Alle",       icon: "◈", count: listings.length },
  { label: "Korallen",   icon: "🪸", count: listings.filter((l) => l.category === "Korallen").length },
  { label: "Fische",     icon: "🐠", count: listings.filter((l) => l.category === "Fische").length },
  { label: "Wirbellose", icon: "🦞", count: listings.filter((l) => l.category === "Wirbellose").length },
  { label: "Equipment",  icon: "💡", count: listings.filter((l) => l.category === "Equipment").length },
  { label: "Frags",      icon: "🪨", count: listings.filter((l) => l.category === "Frags").length },
];
